@extends('layouts.admin')

@section('title', 'Utilisateurs')
@section('page_title', 'Gestion des utilisateurs')

@section('content')
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div><h2 class="text-xl font-bold">Utilisateurs et traçabilité</h2><p class="text-sm text-gray-500">Consultez les comptes, rôles et dernières activités.</p></div>
        <form method="GET" class="flex flex-wrap gap-2"><input name="search" value="{{ request('search') }}" placeholder="Nom ou e-mail..." class="rounded-lg border px-3 py-2 text-sm"><select name="role" class="rounded-lg border px-3 py-2 text-sm"><option value="">Tous les rôles</option><option value="user" @selected(request('role') === 'user')>Citoyen</option><option value="admin" @selected(request('role') === 'admin')>Administrateur</option></select><button class="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white">Filtrer</button></form>
    </div>
    <div class="overflow-hidden rounded-xl bg-white shadow"><table class="w-full text-sm"><thead class="bg-gray-50 text-gray-600"><tr><th class="px-4 py-3 text-left">Utilisateur</th><th class="px-4 py-3 text-left">Rôle</th><th class="px-4 py-3 text-left">Dernière connexion</th><th class="px-4 py-3 text-left">Traçabilité</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y">@forelse($users as $user)<tr class="hover:bg-gray-50"><td class="px-4 py-3"><p class="font-medium">{{ $user->name }}</p><p class="text-xs text-gray-500">{{ $user->email }}</p></td><td class="px-4 py-3"><span class="rounded px-2 py-1 text-xs font-semibold {{ $user->role === 'admin' ? 'bg-violet-100 text-violet-700' : 'bg-emerald-100 text-emerald-700' }}">{{ $user->role === 'admin' ? 'Administrateur' : 'Citoyen' }}</span></td><td class="px-4 py-3">{{ $user->last_login_at?->format('d/m/Y H:i') ?? 'Jamais' }}</td><td class="px-4 py-3">{{ $user->activities_count }} événements · {{ $user->repair_requests_count }} réparations</td><td class="space-x-2 px-4 py-3 text-right"><a href="{{ route('admin.users.show', $user) }}" class="text-blue-600 hover:underline">Historique</a>@if(! $user->is(auth()->user()))<form action="{{ route('admin.users.update', $user) }}" method="POST" class="inline">@csrf @method('PUT')<select name="role" onchange="this.form.submit()" class="rounded border px-2 py-1 text-xs"><option value="user" @selected($user->role === 'user')>Citoyen</option><option value="admin" @selected($user->role === 'admin')>Admin</option></select></form><form action="{{ route('admin.users.destroy', $user) }}" method="POST" class="inline" onsubmit="return confirm('Supprimer ce compte ?')">@csrf @method('DELETE')<button class="text-red-600 hover:underline">Suppr.</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="py-6 text-center text-gray-400">Aucun utilisateur trouvé.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $users->links() }}</div>
@endsection
